mysql:
  image: mysql:5.6.23
  environment:
    MYSQL_ROOT_PASSWORD: 'pass'
  ports:
    - '3306:3306'
  volumes_from:
    - datastore

redis:
  image: redis:2.8.19
  ports:
    - '6379:6379'
  volumes_from:
    - datastore

neo4j:
  image: neo4j
  environment:
    - NEO4J_AUTH=none
    - NEO4J_ALLOW_STORE_UPGRADE=true
  ports:
    - "7474:7474"
  volumes_from:
    - datastore

nginx:
  build: containers/nginx
  ports:
    - '80:80'
  volumes_from:
    - datastore
  links:
    - rails

datastore:
  build: containers/datastore

rails:
  build: .
  ports:
    - '3000:3000'
  environment:
    RAILS_ENV: development
    MYSQL_ROOT_USER: 'routeapi'
    MYSQL_ROOT_PASSWORD: 'routeapi'
    NEO4J_URL: http://neo4j:7474
    DATABASE_URL: mysql2://root:pass@mysql:3306
    REDIS_URL: redis://redis:6379
    SECRET_KEY_BASE: hogehoge
  volumes_from:
    - datastore
  links:
    - mysql
    - redis
    - neo4j
