default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>

development:
  <<: *default
  database: routeapi_development
  host: localhost
  username: routeapi
  password: routeapi

test:
  <<: *default
  database: routeapi_test
  host: <%= ENV['DATABASE_URL'] %>

staging:
  <<: *default
  database: routeapi_staging
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: routeapi_production
  url: <%= ENV['DATABASE_URL'] %>
