default: &default
  type: server_db
  url: <%= ENV['NEO4J_URL'] %>

localhost:
  <<: *default
  url: http://localhost:7474

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
